### ISSUE TITLE
Making on Ubuntu

### ISSUE THREAD

**Issue by SeanTomlinson30** [eyzhao/bio-pipeline-dependencies#2]
Problem is the following:

```
Solving environment: failed

ResolvePackageNotFound: 
  - r::r-rcpp=0.12.10
  - bioconda::r-docopt=0.4.5
``` 

I checked https://anaconda.org/ and the packages are not in their respective channels. Some sleuthing revealed that they are now both located within `conda-forge`. To clarify, I'm talking about the specified versions. #3 respects version requirements.

I have submitted a PR for the environment.yaml changes ref #3

**Comment by eyzhao** [comment]
Thank you Sean! Merged.
